### BusinessException messages

businessException.InternalError.message=The server encountered an internal error or misconfiguration and was unable to complete your request.

# placeholders:
#   {0}: entity
#   {1}: idFieldName
#   {2}: idFieldValue
businessException.NotFound.message={0} with {1} {2} could not be found.
businessException.AlreadyExists.message={0} with {1} {2} already exists.